### ISSUE TITLE
Problème SSL

### ISSUE THREAD

**Issue by TheKillHDmc** [MineWeb/Plugin-XenBridge#3]
Bonjour,

Mon site web est sous protocol SSL mais le plugin ne le détecte pas : 

"PAS OK. Votre site "mineweb" doit être sous un protocole sécurisé SSL (https)."

Site web : https://www.ohminegod.fr

Merci d'avance

**Comment by Quentiin38** [comment]
Également pour moi

https://eredhel.fr
