### ISSUE TITLE
XenBridge ne détecte pas le SSL de mon Site Web. Mais celui de mon forum oui!

### ISSUE THREAD

**Issue by GilloDaby** [MineWeb/Plugin-XenBridge#4]
Allo je ne comprend pas comment cela est possible ! Comme dis dans le site le SSL est détecter sur le forum qui est hébergé sur le site. Mais mon site en lui même n'est pas détecté alors qu'il est sous SSL
Site: https://pvp.cosmos-community.fr/ 
https://i.imgur.com/fEPSoOE.png

**Comment by sadoj-kuro** [comment]
![image](https://user-images.githubusercontent.com/8905889/80059261-96cd9500-84f9-11ea-95da-598abddd9124.png)
et t’espère avoir de l'aide ?
